### PR TITLE
Fix #4

### LINKED ISSUE #4: Laravel 5.2 is now /login not /auth/login
Old
    `return redirect()->guest('auth/login');`

New
        `return redirect()->guest('login');`

Thanks!

### PR DESCRIPTION
**Pull request by canvural**

### CODE REVIEW

**Comment by freekmurze** [comment]
This is a breaking change for existing package users. Could you move the redirection url to a config file.

This way it won't be breaking, Laravel 5.2 user can just update the url in the config file and we're protected against future url changes by the framework.

**Comment by canvural** [comment]
@freekmurze, ok, i done something. You can review.

Ah, i should update README with service provider and publishing the config.

**Comment by freekmurze** [comment]
Looking good. You should indeed update the readme. I have the habit of putting the entire config value in readme, here's an [example](https://github.com/spatie/laravel-feed).

Also rename `default_login_path` to `login_url`, sounds a bit friendlier.

**Comment by canvural** [comment]
Done.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
Your changes are present in the newly tagged version 1.1.0

**Comment by canvural** [comment]
@freekmurze, thanks. 

You renamed the config path. But i guess you forgot to change the path in the service provider.

**Comment by freekmurze** [comment]
Thanks for letting me know.

Fixed in 1.1.1

**Pull request merged**
